//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullardEncuestas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaEvaluador
    {
        public EncuestaEvaluador()
        {
            this.Respuestas = new HashSet<Respuestas>();
        }
    
        public int IdEncuestaEvaluador { get; set; }
        public Nullable<int> IdEncuesta { get; set; }
        public Nullable<int> IdEvaluador { get; set; }
        public Nullable<int> CodEvaluador { get; set; }
        public Nullable<bool> EstadoEncuesta { get; set; }
        public Nullable<int> IdEvaluado { get; set; }
    
        public virtual Encuesta Encuesta { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Persona Persona1 { get; set; }
        public virtual ICollection<Respuestas> Respuestas { get; set; }
    }
}
