//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullardEncuestas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encuesta
    {
        public Encuesta()
        {
            this.EncuestaEvaluador = new HashSet<EncuestaEvaluador>();
            this.Seccion = new HashSet<Seccion>();
            this.GrupoTrabajo1 = new HashSet<GrupoTrabajo>();
        }
    
        public int IdEncuesta { get; set; }
        public string Nombre { get; set; }
        public string Instrucciones { get; set; }
        public string Leyenda { get; set; }
        public int IdPeriodo { get; set; }
        public Nullable<int> IdGrupoEvaluado { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaCierre { get; set; }
    
        public virtual GrupoTrabajo GrupoTrabajo { get; set; }
        public virtual Periodo Periodo { get; set; }
        public virtual ICollection<EncuestaEvaluador> EncuestaEvaluador { get; set; }
        public virtual ICollection<Seccion> Seccion { get; set; }
        public virtual ICollection<GrupoTrabajo> GrupoTrabajo1 { get; set; }
    }
}
