//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullardEncuestas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encuesta
    {
        public Encuesta()
        {
            this.EncuestaEvaluador = new HashSet<EncuestaEvaluador>();
        }
    
        public int IdEncuesta { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdPeriodo { get; set; }
        public Nullable<int> IdGrupoEncuestado { get; set; }
    
        public virtual GrupoTrabajo GrupoTrabajo { get; set; }
        public virtual Periodo Periodo { get; set; }
        public virtual ICollection<EncuestaEvaluador> EncuestaEvaluador { get; set; }
    }
}
