//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullardEncuestas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaEvaluador
    {
        public EncuestaEvaluador()
        {
            this.Respuestas = new HashSet<Respuestas>();
        }
    
        public int IdEncuestaEvaluador { get; set; }
        public int IdEncuesta { get; set; }
        public int IdEvaluador { get; set; }
        public string CodEvaluador { get; set; }
        public bool EstaCompleto { get; set; }
    
        public virtual Encuesta Encuesta { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual ICollection<Respuestas> Respuestas { get; set; }
    }
}
