//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullardEncuestas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoTrabajo
    {
        public GrupoTrabajo()
        {
            this.Encuesta = new HashSet<Encuesta>();
            this.Encuesta1 = new HashSet<Encuesta>();
            this.Persona = new HashSet<Persona>();
        }
    
        public int IdGrupoTrabajo { get; set; }
        public string Nombre { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<Encuesta> Encuesta { get; set; }
        public virtual ICollection<Encuesta> Encuesta1 { get; set; }
        public virtual ICollection<Persona> Persona { get; set; }
    }
}
