//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullardEncuestas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodo
    {
        public Periodo()
        {
            this.Encuesta = new HashSet<Encuesta>();
        }
    
        public int IdPeriodo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Encuesta> Encuesta { get; set; }
    }
}
