//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullardEncuestas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.EncuestaEvaluador = new HashSet<EncuestaEvaluador>();
            this.Respuestas = new HashSet<Respuestas>();
            this.GrupoTrabajo = new HashSet<GrupoTrabajo>();
        }
    
        public int IdPersona { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public bool Estado { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<EncuestaEvaluador> EncuestaEvaluador { get; set; }
        public virtual ICollection<Respuestas> Respuestas { get; set; }
        public virtual ICollection<GrupoTrabajo> GrupoTrabajo { get; set; }
    }
}
