//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullardEncuestas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregunta
    {
        public Pregunta()
        {
            this.Respuestas = new HashSet<Respuestas>();
        }
    
        public int IdPregunta { get; set; }
        public string Texto { get; set; }
        public int IdSeccion { get; set; }
        public int Orden { get; set; }
        public int IdTipoRespuesta { get; set; }
        public bool Estado { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Seccion Seccion { get; set; }
        public virtual TipoRespuesta TipoRespuesta { get; set; }
        public virtual ICollection<Respuestas> Respuestas { get; set; }
    }
}
