//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullardEncuestas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seccion
    {
        public Seccion()
        {
            this.Pregunta = new HashSet<Pregunta>();
            this.Seccion1 = new HashSet<Seccion>();
        }
    
        public int IdSeccion { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdEncuesta { get; set; }
        public Nullable<int> IdSeccionPadre { get; set; }
        public Nullable<int> Orden { get; set; }
    
        public virtual ICollection<Pregunta> Pregunta { get; set; }
        public virtual ICollection<Seccion> Seccion1 { get; set; }
        public virtual Seccion Seccion2 { get; set; }
    }
}
