//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullardEncuestas.Data
{
    using System;
    
    public partial class SP_GetPreguntasEnEncuesta_Result3
    {
        public int IdPregunta { get; set; }
        public string TextoPregunta { get; set; }
        public int IdTipoRespuesta { get; set; }
        public int IdSeccion { get; set; }
        public string NombreSeccion { get; set; }
        public Nullable<decimal> PromedioPregunta { get; set; }
    }
}
