//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullardEncuestas.Data
{
    using System;
    
    public partial class SP_GetEncuestas2_Result2
    {
        public int IdEncuesta { get; set; }
        public string NombreEncuesta { get; set; }
        public int IdPeriodo { get; set; }
        public string NombrePeriodo { get; set; }
        public string NombreGrupo { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> IdGrupoEvaluado { get; set; }
        public Nullable<decimal> PromedioGeneral { get; set; }
    }
}
