//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullardEncuestas.Data
{
    using System;
    
    public partial class SP_GetEncuestasReporteDetalle2_Result2
    {
        public int IdPregunta { get; set; }
        public string TextoPregunta { get; set; }
        public int IdEvaluado { get; set; }
        public string NombreEvaluado { get; set; }
        public Nullable<decimal> PromedioPreguntaXEvaluado { get; set; }
    }
}
