//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullardEncuestas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoRespuesta
    {
        public TipoRespuesta()
        {
            this.OpcionesRespuesta = new HashSet<OpcionesRespuesta>();
        }
    
        public int IdTipoRespuesta { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdPregunta { get; set; }
    
        public virtual ICollection<OpcionesRespuesta> OpcionesRespuesta { get; set; }
        public virtual Pregunta Pregunta { get; set; }
    }
}
